# Generated by Django 4.1.2 on 2023-07-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("acronym", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["name", "acronym"],
            },
        ),
    ]
