# Generated by Django 3.2.15 on 2022-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_of_freshman',
            field=models.CharField(choices=[('1반', '1반'), ('2반', '2반'), ('3반', '3반'), ('4반', '4반'), ('5반', '5반')], default='1반', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contactable_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contactable_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='generation',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_freshman',
            field=models.CharField(choices=[('1번', '1번'), ('2번', '2번'), ('3번', '3번'), ('4번', '4번'), ('5번', '5번'), ('6번', '6번'), ('7번', '7번'), ('8번', '8번'), ('9번', '9번'), ('10번', '10번'), ('11번', '11번'), ('12번', '12번'), ('13번', '13번'), ('14번', '14번'), ('15번', '15번'), ('16번', '16번'), ('17번', '17번'), ('18번', '18번')], default=5, max_length=10),
            preserve_default=False,
        ),
    ]
