# Generated by Django 4.1.1 on 2022-10-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_academicbackground_institution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={"ordering": ["name", "acronym"]},
        ),
    ]
