# Generated by Django 4.1.1 on 2022-10-05 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_academicbackground_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicbackground",
            name="academy_affiliation",
            field=models.CharField(
                choices=[
                    ("NATURAL SCIENCE", "자연과학 계열"),
                    ("ENGINEERING", "공학 계열"),
                    ("MEDICAL", "의학 계열"),
                    ("OTHER FIELDS", "기타 계열"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="academicbackground",
            name="academy_ending_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                default=django.db.models.deletion.SET_NULL,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="career",
            name="career_affiliation",
            field=models.CharField(
                choices=[
                    ("NATURAL SCIENCE", "자연과학 계열"),
                    ("ENGINEERING", "공학 계열"),
                    ("MEDICAL", "의학 계열"),
                    ("OTHER FIELDS", "기타 계열"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="career",
            name="career_ending_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                default=django.db.models.deletion.SET_NULL,
                max_length=10,
                null=True,
            ),
        ),
    ]
