# Generated by Django 4.1.1 on 2022-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20221003_0602"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_year", models.PositiveIntegerField(default=2022)),
                ("ending_year", models.PositiveIntegerField(default=2022)),
                ("institution", models.CharField(max_length=200)),
                ("deparment", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="InterestedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("Architectural Engineering", "건축/건설"),
                            ("Business", "경영학"),
                            ("Economics", "경제학"),
                            ("Pedagogy", "교육학"),
                            ("Mechanical Engineering", "기계"),
                            ("Physics", "물리학"),
                            ("Law", "법학"),
                            ("Industrial Engineering", "산업공학"),
                            ("Industrial Design", "산업디자인"),
                            ("Biotechnology", "생명공학"),
                            ("Biology", "생명과학"),
                            ("Veterinary Medicine", "수의학"),
                            ("Mathematics", "수학"),
                            ("Pharmacy", "약학"),
                            ("Medical Engineeing", "의료공학"),
                            ("Medicine", "의학"),
                            ("Elctrical & Electronic Engineering", "전기전자"),
                            ("Earth Science", "지구과학"),
                            ("Astronomy", "천문학"),
                            ("Dental Medicine", "치의학"),
                            ("Computer Science", "컴퓨터"),
                            ("Korean Medicine", "한의학"),
                            ("Aerospace Engineering", "항공우주공학"),
                            ("Chemistry", "화학"),
                            ("Chemical Engineering", "화학"),
                            ("Environmental Engineering", "환경공학"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RelatedFeild",
        ),
        migrations.AddField(
            model_name="academicbackground",
            name="degree",
            field=models.CharField(
                choices=[
                    ("BS", "이학사"),
                    ("BA", "인문 학사"),
                    ("MS", "이학 석사"),
                    ("MA", "인문학 석사"),
                    ("MBA", "경영학 석사"),
                    ("Ph.D", "박사"),
                ],
                default="BS",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="academicbackground",
            name="ending_year",
            field=models.PositiveIntegerField(blank=True, default=2022, null=True),
        ),
        migrations.AddField(
            model_name="academicbackground",
            name="institution",
            field=models.CharField(
                default="",
                help_text="해외 대학, IST, POSTECH의 경우 영어대문자로 기재바랍니다. 그 외 국내대학교는 **대(ex:서울대)까지만 기재해주세요.",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicbackground",
            name="major",
            field=models.CharField(
                default="",
                help_text="한글로 기재바랍니다. 복수전공의 경우 반점(,)으로 표시해주세요.",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicbackground",
            name="starting_year",
            field=models.PositiveIntegerField(default=2022),
        ),
        migrations.AddField(
            model_name="user",
            name="academic_backgrounds",
            field=models.ManyToManyField(to="users.academicbackground"),
        ),
        migrations.AddField(
            model_name="user",
            name="affiliation",
            field=models.CharField(
                choices=[
                    ("NATURAL SCIENCE", "자연과학"),
                    ("ENGINEERING", "공학 계열"),
                    ("MEDICAL", "의학 계열"),
                    ("OTHER FIELDS", "기타"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cv"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile"),
        ),
        migrations.AddField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="careers",
            field=models.ManyToManyField(to="users.career"),
        ),
        migrations.AddField(
            model_name="user",
            name="interested_fields",
            field=models.ManyToManyField(to="users.interestedfield"),
        ),
    ]
