# Generated by Django 4.1.1 on 2022-10-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_academicbackground_academy_affiliation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicbackground",
            name="academy_ending_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="career",
            name="career_ending_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
