# Generated by Django 4.1.1 on 2022-10-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_academic_backgrounds_remove_user_careers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="generation",
            field=models.CharField(
                choices=[
                    ("1", "1기"),
                    ("2", "2기"),
                    ("3", "3기"),
                    ("4", "4기"),
                    ("5", "5기"),
                    ("6", "6기"),
                    ("7", "7기"),
                ],
                default="1",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
