# Generated by Django 4.1.2 on 2022-10-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_generation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicbackground",
            options={"ordering": ["academy_starting_year", "academy_ending_year"]},
        ),
        migrations.AlterModelOptions(
            name="career",
            options={"ordering": ["career_starting_year", "career_ending_year"]},
        ),
    ]
