# Generated by Django 4.1.2 on 2022-10-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_academicbackground_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cv_link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="github_link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="homepage_link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="insta_link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="linkedin_link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo_link",
            field=models.URLField(max_length=1000),
        ),
    ]
