# Generated by Django 4.1.2 on 2022-10-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_cv_link_alter_user_github_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicbackground",
            name="academy_ending_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="academicbackground",
            name="academy_starting_year",
            field=models.CharField(
                choices=[
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                default="2022",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="career",
            name="career_ending_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="career",
            name="career_starting_year",
            field=models.CharField(
                choices=[
                    ("2014", "2014"),
                    ("2015", "2015"),
                    ("2016", "2016"),
                    ("2017", "2017"),
                    ("2018", "2018"),
                    ("2019", "2019"),
                    ("2020", "2020"),
                    ("2021", "2021"),
                    ("2022", "2022"),
                ],
                default="2022",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="class_of_freshman",
            field=models.CharField(
                choices=[
                    ("1반", "1반"),
                    ("2반", "2반"),
                    ("3반", "3반"),
                    ("4반", "4반"),
                    ("5반", "5반"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="generation",
            field=models.CharField(
                choices=[
                    ("1", "1기"),
                    ("2", "2기"),
                    ("3", "3기"),
                    ("4", "4기"),
                    ("5", "5기"),
                    ("6", "6기"),
                    ("7", "7기"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="number_of_freshman",
            field=models.CharField(
                choices=[
                    ("1번", "1번"),
                    ("2번", "2번"),
                    ("3번", "3번"),
                    ("4번", "4번"),
                    ("5번", "5번"),
                    ("6번", "6번"),
                    ("7번", "7번"),
                    ("8번", "8번"),
                    ("9번", "9번"),
                    ("10번", "10번"),
                    ("11번", "11번"),
                    ("12번", "12번"),
                    ("13번", "13번"),
                    ("14번", "14번"),
                    ("15번", "15번"),
                    ("16번", "16번"),
                    ("17번", "17번"),
                    ("18번", "18번"),
                ],
                max_length=20,
            ),
        ),
    ]
