# Generated by Django 4.1.2 on 2022-10-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_academicbackground_academy_ending_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="career",
            old_name="deparment",
            new_name="department",
        ),
    ]
